server:
  port: 8000
spring:
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/quiz?characterEncoding=utf8&useSSL=false&autoReconnection=true
      username: hope
      password: 1234
      driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 10MB
      file-size-threshold: 1MB
properties:
  file-path: /uploads