/*
 * TB_MEMBER (회원정보)
 */
CREATE TABLE quiz.tb_member (
  member_no INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  id VARCHAR(45) NOT NULL,
  password CHAR(32) NOT NULL,
  status TINYINT(4) NOT NULL DEFAULT 1,
  login_failed_cnt INT NOT NULL DEFAULT 0,
  last_pwd_changed_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  creator INT(10) UNSIGNED NOT NULL,
  updater INT(10) UNSIGNED NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (member_no))
;